CREATE TABLE IF NOT EXISTS uploads
(
    id         INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    image_name VARCHAR(255) NOT NULL UNIQUE,
    alt_text   VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);